# Do not keep production secrets in the repository,
# instead read values from the environment.

# Do not keep production secrets in the repository,
# instead read values from the environment.
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

